#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { Octokit } from '@octokit/rest';
import fetch from 'node-fetch';
import { GoogleGenerativeAI } from '@google/generative-ai';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROMPT_TEMPLATE = `A high-end editorial food photograph of {DISH_NAME}, styled simply and beautifully. The dish is centered on a soft matte ceramic plate or bowl, sitting on a clean off-white surface (#F5F5F7) with subtle warm undertones. Soft, diffused natural daylight from the upper left, gentle shadows, no harsh highlights. Shot from a slight three-quarter overhead angle (about 45 degrees), shallow depth of field, the dish in crisp focus while the surface softly blurs at the edges. Minimal styling — only what naturally belongs with the dish. Warm and appetizing color grading, slightly desaturated, calm and premium mood, in the visual style of Apple's iOS marketing imagery, Bon Appétit, and Apple Fitness app meal cards. Plenty of negative space around the dish for cropping. Photorealistic, sharp, magazine quality. No text, no logos, no watermarks, no brand markings, no hands, no people, no utensils unless essential to the dish, no busy props.`;

class RecipeImageAgent {
  constructor() {
    this.validateEnvironment();
    this.initializeClients();
    const homeDir = process.env.HOME || process.env.USERPROFILE;
    this.assetsDir = path.join(homeDir, 'Desktop', 'smartcart-assets-renamed');
    this.catalogPath = path.join(__dirname, 'SmartCart', 'smartcart_catalog.json');
  }

  validateEnvironment() {
    const required = ['GEMINI_API_KEY', 'GITHUB_TOKEN', 'GITHUB_OWNER', 'GITHUB_REPO'];
    const missing = required.filter(key => !process.env[key]);

    if (missing.length > 0) {
      throw new Error(
        `Missing environment variables: ${missing.join(', ')}\n` +
        'Please create a .env file with: GEMINI_API_KEY, GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO'
      );
    }
  }

  initializeClients() {
    this.genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    this.octokit = new Octokit({
      auth: process.env.GITHUB_TOKEN,
    });
  }

  loadCatalog() {
    try {
      const data = fs.readFileSync(this.catalogPath, 'utf8');
      return JSON.parse(data);
    } catch (error) {
      throw new Error(`Failed to load catalog: ${error.message}`);
    }
  }

  getExistingImageIds() {
    try {
      const files = fs.readdirSync(this.assetsDir);
      const ids = files
        .filter(f => f.match(/^\d+\.jpg$/))
        .map(f => parseInt(f.split('.')[0], 10))
        .sort((a, b) => a - b);
      return new Set(ids);
    } catch (error) {
      console.warn(`⚠️  Could not read assets directory: ${error.message}`);
      return new Set();
    }
  }

  getMissingRecipes(recipes, existingIds) {
    return recipes.filter(recipe => !existingIds.has(recipe.id));
  }

  async generateImageForRecipe(recipeId, recipeName) {
    try {
      const prompt = PROMPT_TEMPLATE.replace('{DISH_NAME}', recipeName);

      console.log(`\n🎨 [${recipeId}] Generating: "${recipeName}"`);

      const model = this.genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

      const result = await model.generateContent({
        contents: [
          {
            role: 'user',
            parts: [
              {
                text: `Generate a photorealistic image of this dish:\n\n${prompt}`,
              },
            ],
          },
        ],
      });

      const response = result.response;

      if (!response || !response.candidates || response.candidates.length === 0) {
        throw new Error('No image generated by API');
      }

      const candidate = response.candidates[0];

      if (!candidate.content || !candidate.content.parts || candidate.content.parts.length === 0) {
        throw new Error('No content in API response');
      }

      const part = candidate.content.parts[0];

      if (part.inlineData) {
        return await this.saveBinaryImage(recipeId, part.inlineData);
      } else {
        throw new Error('No image data in response');
      }
    } catch (error) {
      console.error(`  ✗ Failed: ${error.message}`);
      return null;
    }
  }

  saveBinaryImage(recipeId, inlineData) {
    try {
      const filename = `${recipeId}.jpg`;
      const filepath = path.join(this.assetsDir, filename);

      // Create directory if it doesn't exist
      if (!fs.existsSync(this.assetsDir)) {
        fs.mkdirSync(this.assetsDir, { recursive: true });
      }

      const buffer = Buffer.from(inlineData.data, 'base64');
      fs.writeFileSync(filepath, buffer);

      console.log(`  ✓ Saved: ${filename} (${(buffer.length / 1024).toFixed(1)} KB)`);
      return {
        recipeId,
        filename,
        filepath,
      };
    } catch (error) {
      console.error(`  ✗ Error saving image: ${error.message}`);
      return null;
    }
  }

  async generateBatch(recipes, batchSize = 5) {
    const catalog = this.loadCatalog();
    const existingIds = this.getExistingImageIds();
    const missingRecipes = this.getMissingRecipes(catalog.recipes, existingIds);

    console.log(`\n📊 Status:`);
    console.log(`  Total recipes: ${catalog.recipes.length}`);
    console.log(`  Existing images: ${existingIds.size}`);
    console.log(`  Missing: ${missingRecipes.length}`);
    console.log(`  Batch size: ${batchSize}`);

    // Filter to requested recipes
    const recipesToProcess = recipes || missingRecipes.slice(0, batchSize);

    console.log(`\n🚀 Processing ${recipesToProcess.length} recipes...\n`);

    const generatedFiles = [];
    const failedRecipes = [];

    for (let i = 0; i < recipesToProcess.length; i++) {
      const recipe = recipesToProcess[i];
      const progress = `[${i + 1}/${recipesToProcess.length}]`;

      try {
        const result = await this.generateImageForRecipe(recipe.id, recipe.name);
        if (result) {
          generatedFiles.push(result);
        } else {
          failedRecipes.push({
            id: recipe.id,
            name: recipe.name,
          });
        }
      } catch (error) {
        console.error(`${progress} Error: ${error.message}`);
        failedRecipes.push({
          id: recipe.id,
          name: recipe.name,
          error: error.message,
        });
      }

      // Add small delay between requests to avoid rate limiting
      if (i < recipesToProcess.length - 1) {
        await new Promise(resolve => setTimeout(resolve, 1000));
      }
    }

    return {
      success: generatedFiles.length,
      failed: failedRecipes.length,
      generatedFiles,
      failedRecipes,
    };
  }

  async commitAndPushToGitHub(files, batchInfo) {
    try {
      if (files.length === 0) {
        console.log('⚠️  No files to commit');
        return null;
      }

      console.log('\n📤 Pushing to GitHub...');

      const owner = 'nullclub365-droid';
      const repo = 'smartcart-assets';
      const branch = 'main';

      // Get the latest commit
      const ref = await this.octokit.git.getRef({
        owner,
        repo,
        ref: `heads/${branch}`,
      });

      const baseCommitSha = ref.data.object.sha;

      // Get the current tree
      const baseTree = await this.octokit.git.getTree({
        owner,
        repo,
        tree_sha: baseCommitSha,
        recursive: 1,
      });

      const newTree = [];

      // Add new image files
      for (const file of files) {
        const content = fs.readFileSync(file.filepath);
        const blob = await this.octokit.git.createBlob({
          owner,
          repo,
          content: content.toString('base64'),
          encoding: 'base64',
        });

        newTree.push({
          path: file.filename,
          mode: '100644',
          type: 'blob',
          sha: blob.data.sha,
        });
      }

      // Keep existing files
      for (const item of baseTree.data.tree) {
        if (!newTree.some(t => t.path === item.path)) {
          newTree.push(item);
        }
      }

      // Create new tree
      const tree = await this.octokit.git.createTree({
        owner,
        repo,
        tree: newTree,
      });

      // Create commit
      const commitMessage = `feat: Add ${files.length} generated recipe images\n\n${batchInfo}`;

      const commit = await this.octokit.git.createCommit({
        owner,
        repo,
        message: commitMessage,
        tree: tree.data.sha,
        parents: [baseCommitSha],
      });

      // Update reference
      await this.octokit.git.updateRef({
        owner,
        repo,
        ref: `heads/${branch}`,
        sha: commit.data.sha,
      });

      console.log(`✓ Pushed to ${owner}/${repo}/${branch}`);
      console.log(`✓ Commit: ${commit.data.sha.substring(0, 7)}`);
      console.log(`✓ URL: https://github.com/${owner}/${repo}/commit/${commit.data.sha}`);

      return {
        success: true,
        sha: commit.data.sha,
        url: `https://github.com/${owner}/${repo}/commit/${commit.data.sha}`,
      };
    } catch (error) {
      console.error(`✗ GitHub push failed: ${error.message}`);
      return null;
    }
  }

  async run(batchSize = 5, dryRun = false) {
    try {
      console.log('🍳 SmartCart Recipe Image Generation Agent\n');

      const result = await this.generateBatch(null, batchSize);

      console.log(`\n✅ Generation Complete`);
      console.log(`  Generated: ${result.success}`);
      console.log(`  Failed: ${result.failed}`);

      if (result.failed > 0) {
        console.log(`\n⚠️  Failed recipes:`);
        result.failedRecipes.forEach(r => {
          console.log(`  - [${r.id}] ${r.name}`);
        });
      }

      if (!dryRun && result.success > 0) {
        const batchInfo = `- Generated ${result.success} recipe images\n- Batch size: ${batchSize}\n- Timestamp: ${new Date().toISOString()}`;
        await this.commitAndPushToGitHub(result.generatedFiles, batchInfo);
      } else if (dryRun) {
        console.log('\n🧪 Dry run mode - not pushing to GitHub');
      }

      return result;
    } catch (error) {
      console.error('\n❌ Fatal error:', error.message);
      process.exit(1);
    }
  }
}

// Parse command line arguments
const args = process.argv.slice(2);
const batchSize = parseInt(args[0], 10) || 5;
const dryRun = args.includes('--dry-run');

const agent = new RecipeImageAgent();
agent.run(batchSize, dryRun);
